version: '3.7'
services:
  webhook:
    image: spencerhughes/civturnbot
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - LOGLEVEL=info
    ports:
      - 8080:8080
    volumes:
      - ./config:/config